/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:3e2e2a97-9f56-42a8-8df0-68676a7680c8",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_ywIQU1SuG",
    "aws_user_pools_web_client_id": "2nh7vq6a4egvf30tn9rpcm54mi",
    "oauth": {},
    "aws_user_files_s3_bucket": "amplifyjsdb22d608f3e94d85852ea891d3a9bbca114347-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://f2wig2kp7jfbbkiwr6ey4duzlq.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6zuouu6jpvdhdd63gqxjdmbkea"
};


export default awsmobile;
